### ISSUE TITLE
Could you please tell me the meaning of error code 'EE' ? 

### ISSUE THREAD

**Issue by xcom169** [preda/gpuowl#152]
CLI output: 

[note.txt](https://github.com/preda/gpuowl/files/4588251/note.txt)

020-05-06 19:04:13 gfx803-0 OpenCL args "-DEXP=107760617u -DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=12u -DWEIGHT_STEP=0x1.d4807f0eebed1p+0 -DIWEIGHT_STEP=0x1.17c4b0930d496p-1 -DWEIGHT_BIGSTEP=0x1.ae89f995ad3adp+0 -DIWEIGHT_BIGSTEP=0x1.306fe0a31b715p-1 -DPM1=0 -DAMDGPU=1  -cl-fast-relaxed-math -cl-std=CL2.0 "
2020-05-06 19:04:16 gfx803-0 /tmp/comgr-8a1722/input/CompileSource:55:9: warning: GpuOwl requires OpenCL 200, found 120
#pragma message "GpuOwl requires OpenCL 200, found " STR(__OPENCL_VERSION__)
        ^
1 warning generated.

2020-05-06 19:04:16 gfx803-0 OpenCL compilation in 2.85 s
2020-05-06 19:04:17 gfx803-0 107760617 OK        0 loaded: blockSize 400, 0000000000000003
2020-05-06 19:04:21 gfx803-0 107760617 EE      800   0.00%; 3358 us/it; ETA 4d 04:31; b6f3a09599df4135 (check 1.45s)
2020-05-06 19:04:23 gfx803-0 107760617 OK        0 loaded: blockSize 400, 0000000000000003
2020-05-06 19:04:27 gfx803-0 107760617 EE      800   0.00%; 3358 us/it; ETA 4d 04:30; b6f3a09599df4135 (check 1.43s) 1 errors
2020-05-06 19:04:29 gfx803-0 107760617 OK        0 loaded: blockSize 400, 0000000000000003
2020-05-06 19:04:33 gfx803-0 107760617 EE      800   0.00%; 3358 us/it; ETA 4d 04:31; b6f3a09599df4135 (check 1.45s) 2 errors
2020-05-06 19:04:33 gfx803-0 3 sequential errors, will stop.
2020-05-06 19:04:33 gfx803-0 Exiting because "too many errors"
2020-05-06 19:04:33 gfx803-0 waiting for background GCDs..
2020-05-06 19:04:42 gfx803-0 107760617 P2 GCD: no factor
2020-05-06 19:04:42 gfx803-0 {"status":"NF", "exponent":"107760617", "worktype":"PM1", "B1":"1000000", "B2":"30000000", "fft-length":"6291456", "program":{"name":"gpuowl", "version":""}, "computer":"gfx803-0", "aid":"85D2073756615F2193CD59826C87623D", "timestamp":"2020-05-06 17:04:42 UTC"}
2020-05-06 19:04:42 gfx803-0 Bye

**Comment by selroc** [comment]
Hello, gfx803 should be an RX580, at least mine has that code, and has OpenCL 1.2, that's why you see the warning.

The EE means the residue does not match, I guess those boards are no longer supported...

**Comment by xcom169** [comment]
Hello!

I have XFX RX480 GTR 8GB card and Rocm 3.3 installed to Manjaro Linux.

So it's not a hardware issue, but an issue with the OpenCL driver?

**Comment by valeriob01** [comment]
> Hello!
> 
> I have XFX RX480 GTR 8GB card and Rocm 3.3 installed to Manjaro Linux.
> 
> So it's not a hardware issue, but an issue with the OpenCL driver?

gpuowl needs now OpenCL 2.0, your board has 1.2

**Comment by xcom169** [comment]
By specification I think it can do OpenCL 2.0 : 

https://www.techpowerup.com/gpu-specs/radeon-rx-480.c2848

Maybe this Rocm 3.3 only provides OpenCL 1.2 version for now? 

With a different card gpuowl can work flawlessly with ROCm driver?

**Comment by valeriob01** [comment]
ROCm 3.3 provides OpenCL 2.0 or maybe 2.2 I don't remember, but it is better that Preda responds on this topic, he is more aware than me.
A card that works flawlessly is Vega64 and Radeon VII.

**Comment by valeriob01** [comment]
BTW, I am both selroc and valeriob01. Different accounts for different works.

**Comment by preda** [comment]
ROCm 3.3 should be good. EE means "error detected". In this situation it could be a software (gpuowl) problem, as you are using a FFT size that didn't get extensive testing. You can experiment with different FFT sizes (-fft) to see if something works. Anyway, please don't do any LL or P-1 before first validating that PRP works correctly. I'll have a look to see if I can repro on your exponent, but I need a bit of time.

**Comment by xcom169** [comment]
Clinfo output: 
[nano.txt](https://github.com/preda/gpuowl/files/4592773/nano.txt)

**Comment by valeriob01** [comment]
> By specification I think it can do OpenCL 2.0 :
> 
> https://www.techpowerup.com/gpu-specs/radeon-rx-480.c2848
> 
> Maybe this Rocm 3.3 only provides OpenCL 1.2 version for now?
> 
> With a different card gpuowl can work flawlessly with ROCm driver?
> 
> I will try to provide you Clinfo ouptut.

maybe the card provides both OpenCL 1.2 and 2.0 , I don't know, effectively the specification is 2.0

**Comment by xcom169** [comment]
PRP test seems to be working. 

2020-05-07 14:02:46 gpuowl 
2020-05-07 14:02:46 config: -prp 9553977 
2020-05-07 14:02:46 device 0, unique id ''
2020-05-07 14:02:46 gfx803-0 9553977 FFT: 512K 256:4:256 (18.22 bpw)
2020-05-07 14:02:46 gfx803-0 Expected maximum carry32: 158F0000
2020-05-07 14:02:46 gfx803-0 OpenCL args "-DEXP=9553977u -DWIDTH=256u -DSMALL_HEIGHT=256u -DMIDDLE=4u -DWEIGHT_STEP=0x1.b6be6bba2ecdp+0 -DIWEIGHT_STEP=0x1.2abe69c4c283p-1 -DWEIGHT_BIGSTEP=0x1.ae89f995ad3adp+0 -DIWEIGHT_BIGSTEP=0x1.306fe0a31b715p-1 -DPM1=0 -DAMDGPU=1  -cl-fast-relaxed-math -cl-std=CL2.0 "
2020-05-07 14:02:49 gfx803-0 /tmp/comgr-81f7f4/input/CompileSource:55:9: warning: GpuOwl requires OpenCL 200, found 120
#pragma message "GpuOwl requires OpenCL 200, found " STR(__OPENCL_VERSION__)
        ^
1 warning generated.

2020-05-07 14:02:49 gfx803-0 OpenCL compilation in 2.79 s
2020-05-07 14:02:49 gfx803-0 9553977 OK        0 loaded: blockSize 400, 0000000000000003
2020-05-07 14:02:50 gfx803-0 9553977 OK      800   0.01%;  342 us/it; ETA 0d 00:54; 342361c4e48bbe4b (check 0.15s)
2020-05-07 14:04:00 gfx803-0 9553977 OK   200000   2.09%;  351 us/it; ETA 0d 00:55; 3bbd9d776b07c9a5 (check 0.17s)
2020-05-07 14:05:09 gfx803-0 9553977 OK   400000   4.19%;  346 us/it; ETA 0d 00:53; 367271f840bcc065 (check 0.18s)
2020-05-07 14:06:18 gfx803-0 9553977 OK   600000   6.28%;  344 us/it; ETA 0d 00:51; f8c6b1e6bff2bdb1 (check 0.17s)
2020-05-07 14:07:27 gfx803-0 9553977 OK   800000   8.37%;  343 us/it; ETA 0d 00:50; 4406faabfcd3b340 (check 0.17s)
2020-05-07 14:08:36 gfx803-0 9553977 OK  1000000  10.47%;  342 us/it; ETA 0d 00:49; 4dc669282d99bec7 (check 0.18s)
2020-05-07 14:09:44 gfx803-0 9553977 OK  1200000  12.56%;  340 us/it; ETA 0d 00:47; 19092dd1cff1574e (check 0.17s)
2020-05-07 14:10:52 gfx803-0 9553977 OK  1400000  14.65%;  339 us/it; ETA 0d 00:46; 3bb2bc94a87864e5 (check 0.18s)
2020-05-07 14:12:00 gfx803-0 9553977 OK  1600000  16.75%;  341 us/it; ETA 0d 00:45; dba4d67a2ffdd855 (check 0.17s)
2020-05-07 14:13:09 gfx803-0 9553977 OK  1800000  18.84%;  341 us/it; ETA 0d 00:44; 850452f6b36eb42a (check 0.17s)
2020-05-07 14:14:17 gfx803-0 9553977 OK  2000000  20.93%;  341 us/it; ETA 0d 00:43; c90e4f4d38c094ac (check 0.15s)
2020-05-07 14:15:25 gfx803-0 9553977 OK  2200000  23.03%;  341 us/it; ETA 0d 00:42; a2706ad4a48a3be7 (check 0.17s)
2020-05-07 14:15:58 gfx803-0 Stopping, please wait..
2020-05-07 14:15:59 gfx803-0 9553977 OK  2297600  24.05%;  341 us/it; ETA 0d 00:41; 650b189bcb4e16d7 (check 0.16s)
2020-05-07 14:15:59 gfx803-0 Exiting because "stop requested"
2020-05-07 14:15:59 gfx803-0 Bye

**Comment by selroc** [comment]
> > By specification I think it can do OpenCL 2.0 :
> > https://www.techpowerup.com/gpu-specs/radeon-rx-480.c2848
> > Maybe this Rocm 3.3 only provides OpenCL 1.2 version for now?
> > With a different card gpuowl can work flawlessly with ROCm driver?
> > I will try to provide you Clinfo ouptut.
> 
> maybe the card provides both OpenCL 1.2 and 2.0 , I don't know, effectively the specification is 2.0

As you can see Preda's knowledge goes beyond mine, the warning however should mean that only OpenCL 1.2 is available ??

**Comment by dgcampea** [comment]
ROCm reporting OpenCL 1.2 is a bug. It's actually using 2.0 (see https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues/69)

clinfo output (note **Device Version** and **Device OpenCL C Version**):
```
  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx803
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 
  Driver Version                                  3098.0 (HSA1.1,LC)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Board Name (AMD)                         Fiji [Radeon R9 FURY / NANO Series]
```

**Comment by dgcampea** [comment]
> Hello, gfx803 should be an RX580
It can also be a Fury card (Fury X reported as gfx803-0)

> The EE means the residue does not match, I guess those boards are no longer supported...
ROCm supports GFX8 and GFX9 (Fury, Polaris, Vega)

**Comment by selroc** [comment]
> > Hello, gfx803 should be an RX580
> 
> It can also be a Fury card (Fury X reported as gfx803-0)
> 
> > The EE means the residue does not match, I guess those boards are no longer supported...
> 
> ROCm supports GFX8 and GFX9 (Fury, Polaris, Vega)

I did not know about Fury. Thank you.

**Comment by selroc** [comment]
> ROCm reporting OpenCL 1.2 is a bug. It's actually using 2.0 (see [RadeonOpenCompute/ROCm-OpenCL-Runtime#69](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues/69))
> 
> clinfo output (note **Device Version** and **Device OpenCL C Version**):
> 
> ```
>   Platform Name                                   AMD Accelerated Parallel Processing
> Number of devices                                 1
>   Device Name                                     gfx803
>   Device Vendor                                   Advanced Micro Devices, Inc.
>   Device Vendor ID                                0x1002
>   Device Version                                  OpenCL 1.2 
>   Driver Version                                  3098.0 (HSA1.1,LC)
>   Device OpenCL C Version                         OpenCL C 2.0 
>   Device Type                                     GPU
>   Device Board Name (AMD)                         Fiji [Radeon R9 FURY / NANO Series]
> ```

Should we submit an issue to github ?

**Comment by dgcampea** [comment]
> Should we submit an issue to github ?

The issue already exists (see link).
Doubt it's actually causing the EE errors here though.

**Comment by valeriob01** [comment]
> > Should we submit an issue to github ?
> 
> The issue already exists (see link).
> Doubt it's actually causing the EE errors here though.

As Preda said it can be an FFT issue.

**Comment by xcom169** [comment]
PRP worked for me: 

2020-05-07 18:26:29 gpuowl 
2020-05-07 18:26:29 config: -prp 9553977 
2020-05-07 18:26:29 device 0, unique id ''
2020-05-07 18:26:29 gfx803-0 9553977 FFT: 512K 256:4:256 (18.22 bpw)
2020-05-07 18:26:29 gfx803-0 Expected maximum carry32: 158F0000
2020-05-07 18:26:29 gfx803-0 OpenCL args "-DEXP=9553977u -DWIDTH=256u -DSMALL_HEIGHT=256u -DMIDDLE=4u -DWEIGHT_STEP=0x1.b6be6bba2ecdp+0 -DIWEIGHT_STEP=0x1.2abe69c4c283p-1 -DWEIGHT_BIGSTEP=0x1.ae89f995ad3adp+0 -DIWEIGHT_BIGSTEP=0x1.306fe0a31b715p-1 -DPM1=0 -DAMDGPU=1  -cl-fast-relaxed-math -cl-std=CL2.0 "
2020-05-07 18:26:32 gfx803-0 /tmp/comgr-c8859a/input/CompileSource:55:9: warning: GpuOwl requires OpenCL 200, found 120
#pragma message "GpuOwl requires OpenCL 200, found " STR(__OPENCL_VERSION__)
        ^
1 warning generated.

2020-05-07 18:26:32 gfx803-0 OpenCL compilation in 3.05 s
2020-05-07 18:26:33 gfx803-0 9553977 OK  7811200 loaded: blockSize 400, ff06d72c2b0c57b1
2020-05-07 18:26:33 gfx803-0 9553977 OK  7812000  81.77%;  341 us/it; ETA 0d 00:10; f1b8b4c35ea5db7d (check 0.16s)
2020-05-07 18:27:38 gfx803-0 9553977 OK  8000000  83.73%;  344 us/it; ETA 0d 00:09; 5bfeb665f284b6b4 (check 0.16s)
2020-05-07 18:28:49 gfx803-0 9553977 OK  8200000  85.83%;  356 us/it; ETA 0d 00:08; 82c75434aa98d8f0 (check 0.17s)
2020-05-07 18:29:59 gfx803-0 9553977 OK  8400000  87.92%;  345 us/it; ETA 0d 00:07; d7e4d9c5525b3d8c (check 0.17s)
2020-05-07 18:31:07 gfx803-0 9553977 OK  8600000  90.01%;  342 us/it; ETA 0d 00:05; b70aa920f0238ae1 (check 0.18s)
2020-05-07 18:32:17 gfx803-0 9553977 OK  8800000  92.11%;  349 us/it; ETA 0d 00:04; c26f3dd10c07bfe0 (check 0.18s)
2020-05-07 18:33:27 gfx803-0 9553977 OK  9000000  94.20%;  348 us/it; ETA 0d 00:03; 7382f35207d40a9f (check 0.18s)
2020-05-07 18:34:36 gfx803-0 9553977 OK  9200000  96.29%;  346 us/it; ETA 0d 00:02; 9371f90ddd8f8de8 (check 0.16s)
2020-05-07 18:35:48 gfx803-0 9553977 OK  9400000  98.39%;  357 us/it; ETA 0d 00:01; aa71fa349474c486 (check 0.17s)
2020-05-07 18:36:42 gfx803-0 CC  9553977 / 9553977, ca43b3a0b79a7554
2020-05-07 18:36:42 gfx803-0 {"status":"C", "exponent":"9553977", "worktype":"PRP-3", "res64":"ca43b3a0b79a7554", "residue-type":"1", "errors":{"gerbicz":"0"}, "fft-length":"524288", "program":{"name":"gpuowl", "version":""}, "computer":"gfx803-0", "timestamp":"2020-05-07 16:36:42 UTC"}
2020-05-07 18:36:42 gfx803-0 Bye

**Comment by a-repko** [comment]
A similar problem on Vega was solved by `-use ORIG_SLOWTRIG` for me
#117
However, I didn't try your particular exponent, as I'm currently recompiling my OpenCL). You can simply create a config.txt file, which contains just `-use ORIG_SLOWTRIG`, and put it in gpuowl directory.

By the way, this is probably not the Fury/Fury X/Nano card, since these have 56/64 CU and 4GB memory. Your has 36 CU and 8GB memory (according to posted clinfo), which corresponds to RX480 or RX580.

Also please note that the P-1 calculation which you did before is almost certainly wrong. For this reason it is always better to run a bit of PRP for given exponent to be sure of correct calculation (i.e. lines with OK), and only then start the P-1.

**Comment by xcom169** [comment]
Thanks, I'll try. 
However I still don't quite understand the parameters.
As I know -> The smallest composite Mersenne number with prime exponent n is 211 − 1 = 2047 = 23 × 89.  .

So how can I check this: 
]$ ./gpuowl -pm1 11

or 
 ./gpuowl -prp 11

or
./gpuowl -prp 2047
?

**Comment by preda** [comment]
That would be gpuowl -prp 11 if it worked, but gpuowl does not handle such small exponents. If you invoke gpuowl -h, you should see the list of FFT sizes supported together with ranges, and thus an indication of the smallest exponent that can be done with gpuowl.

**Comment by preda** [comment]
Please reopen if anything is left to do here.
